[build]
builder = "NIXPACKS"
watchPatterns = ["ChemicalEquipmentParameterVisualizer/ChemicalEquipmentParameterVisualizer/backend/**"]

[deploy]
startCommand = "cd ChemicalEquipmentParameterVisualizer/ChemicalEquipmentParameterVisualizer/backend && gunicorn equipment_api.wsgi:application --bind 0.0.0.0:$PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
